### ISSUE TITLE
楼主 ，什么时候出最新版

### ISSUE THREAD

**Issue by Liesport758** [cn-src/aliyun-sms#10]
阿里短信出新版了，那对应的springboot版本什么时候出

**Comment by cn-src** [comment]
看了下阿里云新版的 Java SDK，好像是一个通用型的阿里云 api http 客户端，目前没有细化到 sms 之类的。我先了解下。

**Comment by cn-src** [comment]
已更新了一版新 SDK 实现

**Comment by Liesport758** [comment]
好的，楼主
